export const EmployeePosition = Object.freeze({
    SCRUM_MASTER: 'SCRUM_MASTER',
    PRODUCT_OWNER: 'PRODUCT_OWNER',
    FRONTEND_DEVELOPER: 'FRONTEND_DEVELOPER',
    BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
    CEO: 'CEO'
})